In [6]:
import pandas as pd
import numpy as np

df = pd.read_csv('messy_data.csv')
df.head()

   ID        Date  Temperature  Humidity      City    Status Sensor_Code
0   1  2026-01-01         19.4      61.0     Paris    Active       SN001
1   2         NaN         33.8       NaN  New York       NaN       SN002
2   3  2026-01-03         28.3      78.0     Paris  Inactive       SN003
3   4  2026-01-04         25.0      61.0     Paris    Active       SN004
4   5  2026-01-05         13.9      33.0     Paris    Active       SN005

In [7]:
# Convert empty strings or just spaces to True NaN objects
df.replace(r'^\s*$', np.nan, regex=True, inplace=True)

     ID        Date  Temperature  Humidity      City    Status Sensor_Code
0     1  2026-01-01         19.4      61.0     Paris    Active       SN001
1     2         NaN         33.8       NaN  New York       NaN       SN002
2     3  2026-01-03         28.3      78.0     Paris  Inactive       SN003
3     4  2026-01-04         25.0      61.0     Paris    Active       SN004
4     5  2026-01-05         13.9      33.0     Paris    Active       SN005
..  ...         ...          ...       ...       ...       ...         ...
95   96  2026-04-06         22.3      45.0     Tokyo    Active       SN096
96   97  2026-04-07          NaN      58.0       NaN    Active       SN097
97   98  2026-04-08         20.7       NaN     Paris  Inactive         NaN
98   99  2026-04-09         10.6      49.0    London    Active       SN099
99  100  2026-04-10         12.7       NaN       NaN       NaN         NaN

[100 rows x 7 columns]

In [8]:
total_rows = len(df['ID'])
for column in df.columns:
    complete_rows = df[column].count()
    missing_rows = total_rows - complete_rows
    print(f"There are {missing_rows} missing values in {column} column.")

There are 0 missing values in ID column.
There are 15 missing values in Date column.
There are 15 missing values in Temperature column.
There are 15 missing values in Humidity column.
There are 15 missing values in City column.
There are 15 missing values in Status column.
There are 15 missing values in Sensor_Code column.

In [9]:
# using pandas method
missing_counts = df.isnull().sum()
print(missing_counts)

ID              0
Date           15
Temperature    15
Humidity       15
City           15
Status         15
Sensor_Code    15
dtype: int64